### ISSUE TITLE
Align content in GH Pages +  Canvas 

### ISSUE THREAD

**Issue by nniiicc** [nniiicc/LIS-570-Au2020#1]
Create the following links from Site to Canvas 
- [ ] Syllabus links to site (edit the link in Canvas to point to Syllabus page on Site)
- [ ] Assignment links to site (Edit the assignments link to point to Assignment page on Site) 
- [ ] All topic links on home page of site line up with all links for Modules in Canvas (For example - the link to week 1 Module in Canvas should point at the first link on  the site - see screenshot link below) 

https://github.com/nniiicc/LIS-570-Au2020/blob/master/Class-sched.jpg 

In Canvas
- [ ] Erase all photos from front page (masthead, instructor, ta, etc.) 
- [ ] In masthead - enter info about instructor and TA (you!) - my office hours are by appointment only

**Comment by wanchen23** [comment]
Done! -- Wan-Chen

**Comment by cmcd276** [comment]
done!
