### ISSUE TITLE
peer review process / spreadsheet

### ISSUE THREAD

**Issue by cmcd276** [nniiicc/LIS-570-Au2020#10]
three-sheet spreadsheet (which includes examples) can be found here: https://docs.google.com/spreadsheets/d/1JGr9gT1YuncfDnNlqNas7Rh6l6itcdx38gI6crLmzQs/edit?usp=sharing

the spreadsheet is meant to be used for two purposes:
1. recording projects and their authors
2. matching projects w peer reviewers

when students decide on a group for their project, they can enter their group members' names and their project's working title into the first sheet; individual projects should also be added into the spreadsheet. project-making entities will then sign up to review projects within the same document, so that the groups/reviewers are all documented in the same location.

**Comment by nniiicc** [comment]
Notes: 
- Students enter link to their public Lit review draft... 
- We assign students by group number to do peer review
- each student in the group does their own individual review...

**Comment by nniiicc** [comment]
Feedback for peer review: 
1. Paraphrase in 1 paragraph - What the project is about
2. Paragraph on why the topic is important or who is the audience. 
2. Execute search along lines of the project topic ... Suggest two additional pieces of lit and explain in 1-2 sentences why you recommended this.

**Comment by cmcd276** [comment]
link for LIS 570A: https://docs.google.com/spreadsheets/d/1JGr9gT1YuncfDnNlqNas7Rh6l6itcdx38gI6crLmzQs/edit?usp=sharing

link for LIS 570B: https://docs.google.com/spreadsheets/d/1gx-H6lSbO6vj8UcDt9T96TXLFRjhjBoK0j_0-pzQQ-M/edit?usp=sharing

**Comment by nniiicc** [comment]
We still need write up of the process for the Assignment page
