### ISSUE TITLE
recommended readings

### ISSUE THREAD

**Issue by cmcd276** [nniiicc/LIS-570-Au2020#11]
### for research ethics: 

Indian Health Service. Indian Health Service Institutional Review Boards (IRB) Available at: https://www.ihs.gov/dper/research/hsrp/instreviewboards/ 

Morton, Deborah J., Proudfit, Joely, Calac, Daniel, Portillo, Martina, Lofton-Fitzsimmons, Geneva, Molina, Theda, Majel-McCauley, Romelle. (2013). Creating research capacity through a tribally based institutional review board. _The American Journal of Public Health_, 103(12), 2160

**Comment by nniiicc** [comment]
Thanks - added these to next weeks readings.
