### ISSUE TITLE
Readings for Syllabus

### ISSUE THREAD

**Issue by nniiicc** [nniiicc/LIS-570-Au2020#12]
With remaining time from our meeting this week - it would be super helpful if you have readings that you like in this area, readings that you find that look helpful, or readings for an LIS spotlight. These are the remaining topics I need lit for: 

Research design (that is how to design research rather than design based research)
- Topics include sampling, etc. 

Quant data collection 
Quant analysis 

Qual data collection 
Qual analysis 

Design methods 

Reporting

**Comment by wanchen23** [comment]
Costello, L., McDermott, M.-L., & Wallace, R. (2017). Netnography: Range of Practices, Misperceptions, and Missed Opportunities. International Journal of Qualitative Methods, 16(1), 1609406917700647. https://doi.org/10.1177/1609406917700647 

Nowell, L. S., Norris, J. M., White, D. E., & Moules, N. J. (2017). Thematic Analysis: Striving to Meet the Trustworthiness Criteria. International Journal of Qualitative Methods, 16(1), 1609406917733847. https://doi.org/10.1177/1609406917733847 

Charmaz, K., & Belgrave, L. L. (2019). Thinking About Data With Grounded Theory. Qualitative Inquiry, 25(8), 743–753. https://doi.org/10.1177/1077800418809455

Paulus, T. M., Jackson, K., & Davidson, J. (2017). Digital Tools for Qualitative Research: Disruptions and Entanglements. Qualitative Inquiry, 23(10), 751–756. https://doi.org/10.1177/1077800417731080
