### ISSUE TITLE
1/3 survey

### ISSUE THREAD

**Issue by nniiicc** [nniiicc/LIS-570-Au2020#14]
In google forms create a survey: 

1-5 scale questions: 
- I find lectures helpful 
- Lecture length 
- I find chapters helpful 

One thing I would like to see change

Overall this course

**Comment by nniiicc** [comment]
Discussion sections - 
Office hours -

**Comment by nniiicc** [comment]
Questions 1-4 are on a five point scale with 1 being not meeting expectations and 5 being exceeding expectations 

Question 0: I am in Section [A / B] 

Question 1: 
Overall, I find the class (Not meeting expectations / Exceeding Expectations) 

Question 2: 
Overall, I find the lectures (Not meeting expectations / Exceeding Expectations) 

Question 3: 
Overall, I find the readings (Not meeting expectations / Exceeding Expectations) 

Question 4:
Overall, I find the discussion section (Not meeting expectations / Exceeding Expectations) 

Question 5:
If I could change one thing about the overall class, or make one request it would be: [Short Answer]

**Comment by wanchen23** [comment]
Survey link: https://forms.gle/Sgttu6SXixyzw2r37
