### ISSUE TITLE
Readings for Week 6

### ISSUE THREAD

**Issue by nniiicc** [nniiicc/LIS-570-Au2020#16]

**Comment by wanchen23** [comment]
Examples for participant observation:
Bullard, J. (2017), Warrant as a means to study classification system design, Journal of Documentation, 73(1), 75-90. https://doi.org/10.1108/JD-06-2016-0074

Lee, W.-C. (2019). Cataloging practices through an ethnographic lens: Workarounds, disagreements, and manifestations of culture. In Proceedings from North American Symposium of Knowledge Organization, vol. 7. (pp. 129-137). (Philadelphia, Pennsylvania). Retrieved from https://journals.lib.washington.edu/index.php/nasko/article/view/15633/13015 
--> I was re-reading this paper and saw that it argued for the strength of using ethnography  ("This study contributes to the knowledge organization literature by presenting cataloging scenarios on three topics that require prolonged engagement to study."). This might serve our purpose.

**Comment by nniiicc** [comment]
Perfect - thanks!

**Comment by cmcd276** [comment]
examples of LIS-focused document/content analysis:

de Bruin, J., & Mane, J. (2018). Indigenous radio and digital media: Tautoko FM’s national and transnational audiences. _Radio Journal_, 16(2), 127-140.

Feinberg, M. (2017). Reading databases: Slow information interactions beyond the retrieval paradigm. _Journal of Documentation_, 73(2), 336-356.

Hinzo, Angel M, & Clark, Lynn Schofield. (2019). Digital survivance and Trickster humor: Exploring visual and digital Indigenous epistemologies in the #NoDAPL movement. _Information, Communication & Society_, 22(6), 791-807.

**Comment by nniiicc** [comment]
I asked you to do this Friday
