### ISSUE TITLE
Post recordings of Class Discussion Sections

### ISSUE THREAD

**Issue by nniiicc** [nniiicc/LIS-570-Au2020#19]
@wanchen23 + @cmcd276  - can you please check if you have access to LIS 570 class discussion recordings? If you do can you upload them to the drive folder below and let me know when you have done so: 

https://drive.google.com/drive/folders/1xbSf-gFL6QoxnTtIq3inpD0ymNIq2dR5?usp=sharing

**Comment by wanchen23** [comment]
I checked my Zoom cloud recording space but do not see any recordings for the discussion sessions.

**Comment by nniiicc** [comment]
Ok thanks - I'll try to post these later tonight.
