### ISSUE TITLE
Assign NW 1/3 of class section to grade 

### ISSUE THREAD

**Issue by nniiicc** [nniiicc/LIS-570-Au2020#20]
Please add as a response below which project numbers (e.g. Group 21-26) I should be grading.

**Comment by wanchen23** [comment]
For section B, the latter 1/3 is group 15 - 21. Thank you for helping with the grading!

**Comment by cmcd276** [comment]
for section a, i picked groups 7--12, 14, 16 as the middle 1/3 using the group numbers in the peer review spreadsheet. an easier-to-read list is [here](https://docs.google.com/document/d/1M9mFaJbcO_atwVk1ZoPdknolAPYXrSZXsNED-g8WyOo/edit?usp=sharing)

**Comment by nniiicc** [comment]
PERFECT!  🏋️⏳☕... Thanks for getting this figured out today.
