### ISSUE TITLE
Create Assignments in Canvas 

### ISSUE THREAD

**Issue by nniiicc** [nniiicc/LIS-570-Au2020#3]
Create the following assignments with the following due dates and points. For right now - you don't need to input any text about the assignments. 

Research / Evaluation Problem Statement - Draft 
- - Due Oct 15
- - Points 10 

Research / Evaluation Problem Statement - Final 
- - Final Due Dec 4
- - Points 20 

Literature Review Draft  
- - Due Oct 30 
- - Points 10 

Literature Review - Peer Review
- - Due November 6
- - Points 5

Literature Review - Final 
- - Due December 4
- - Points 20 

Data Collection and Analysis Protocol - Draft
- - Nov 13
- - 10 

Data Collection and Analysis Protocol - Final
- - December 4
- - 20

**Comment by nniiicc** [comment]
Time estimate 1 hour

**Comment by cmcd276** [comment]
@nniiicc i had already published these assignments on canvas with the assignment description linking out to the course site. is there anything that needs to be added/changed, other than adding the rubrics / peer review process documents?

**Comment by nniiicc** [comment]
No - I think that should be good.

**Comment by nniiicc** [comment]
But note - I am eliminating the peer review for the final project.
