### ISSUE TITLE
Create discussion forums 

### ISSUE THREAD

**Issue by nniiicc** [nniiicc/LIS-570-Au2020#4]
Please create the following discussion forums in Canvas. Make sure these are Public and enable Threaded Replies and Likes. 

**Introductions**

Text: Please introduce yourself to the class. Tell us: 1. Where you are in the world, 2. What you are interested in pursuing in LIS, and 3. Your score on this quiz https://isthisasandwich.netlify.app/ 

**Research Topic Discussions & Group Finding**

Text: Throughout the quarter we will complete three assignments that are about a single research topic. Please read the assignment overview page on our course site first... Then if you are interested in working with a group, post here about a topic you are interested in working on. Note - you do not HAVE to work in a group, but we recommend it. Here is an example of what you might post (e.g. think of a research topic post going form general to more specific.)  

1. I am interested in academic libraries 
2. In particular I am interested in digital literacy education in public university libraries 
3. An emergent problem for digital literacy in public universities is the ability for freshmen students to assess reliable research findings in online resources. The research project I would like to work on is about literacy levels of freshmen at public universities, and what libraries have found impactful to improving digital literacy. 

**Class Questions and Comments**
Text: Ask any questions about class or assignments here. 

**LIS Research News**
Text: Share any interesting articles or ideas about research here.

**Comment by nniiicc** [comment]
Time estimate - 30 min

**Comment by wanchen23** [comment]
Done!

**Comment by cmcd276** [comment]
done!
