### ISSUE TITLE
Quant Podcast... 

### ISSUE THREAD

**Issue by nniiicc** [nniiicc/LIS-570-Au2020#7]
- Murder episode from You're wrong about this @cmcd276

**Comment by cmcd276** [comment]
Hobbes, M. & Marshall, S. (2020, Jul. 27). Murder. _You're wrong about_ [audio podcast]. 
https://www.buzzsprout.com/1112270/4721657-murder?play=true
^ this episode link also links out to the same episode on multiple listening platforms and the sources cited in the podcast

recommended listening for week 7 (quantitative data analysis): 
the episode begins with the question relating to the frequency of homicides being solved over time, and continues on to engage with relationships between the findings from numerous different quantitative datasets relating to homicide. the discussion does not involve any graphic details about homicides themselves; the hosts are mostly engaged with how data is collected and interpreted in strategic ways to answer questions about homicides, and the broader social implications of conclusions made from these datasets. towards the end of the episode, there is a somewhat graphic description of an example of police brutality.
